sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: fkXPwhknxyYukzZhVBmHrUdO0qj1nCRNmYtcm3NNA2kJ+7ZATDRIDvByOlQKbm0EeiKlN2bg++/UZD/Bo8Qird4zGBEnN2dcE7EYY+iuxYCaH1iT7jpzdxknntwUFOWspoDOAqP4phEG+s27Pe0fceizWvmxi4VaQKzhcUzsd60=
